# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-31bd7d85-5d01-4119-8ec9-bdb2134abdf5";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-31bd7d85-5d01-4119-8ec9-bdb2134abdf5".device = "/dev/disk/by-uuid/31bd7d85-5d01-4119-8ec9-bdb2134abdf5";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D86D-8EF8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/games" = {
    device = "/dev/disk/by-uuid/E69EE9D39EE99C75";
    fsType = "ntfs3";
    options = [
      "defaults"
      "nofail"
      "x-gvfs-show"
      "uid=1000"
      "gid=100"
      "dmask=007"
      "fmask=117"
      "windows_names"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
