{ config, pkgs, inputs, ... }:

{
  environment.systemPackages = with pkgs; [
    wget
    btop
    impala
    neovim
    tree-sitter
    unzip
    fastfetch
    bluetui
    wiremix
    librewolf
    qutebrowser
    waywall
    waybar
    prismlauncher
    nitch
    hyprlock
    hyprsunset
    hypridle
    swaybg
    git
    lazygit
    clang
    walker
    elephant
    zoxide
    wireplumber
    brightnessctl
    playerctl
    grim
    slurp
    satty
    wl-clipboard
    mako
    hyprpicker
    jq
    uwsm
    tmux
    kitty
    inputs.workmux.packages.${pkgs.pkgs.stdenv.hostPlatform.system}.default
    libnotify
    findutils
    power-profiles-daemon
    piper
    bottles
    jq
    ripgrep
    fd
    lazygit
    go
    gopls
    gammastep
    lua-language-server
    imagemagick
    ghostscript
    tectonic
    mermaid-cli
    trash-cli
    sqlite
    vesktop
    steam-run
    inputs.millennium.packages."${pkgs.pkgs.stdenv.hostPlatform.system}".millennium-steam
    samrewritten
    cliamp
    nautilus
    gnome-calculator
    gnome-disk-utility
    galaxy-buds-client
    gale
    kdePackages.kdenlive
    obs-studio
    pinta
    telegram-desktop
    libreoffice
    mullvad-vpn
    mpv
    normcap
    nodejs
    inputs.openlogi.packages.${pkgs.pkgs.stdenv.hostPlatform.system}.default
    yaru-theme
    glfw3-minecraft
    jellyfin-desktop
    opencode
    ollama
    docker
    proton-vpn
    jdk21
    (python3.withPackages (ps: with ps; [
      tkinter
    ]))
  ];
}
